version: "3"
services:
    mlsb:
        environment:
            - ADMIN=$ADMIN
            - PASSWORD=$PASSWORD
            - KIK=$KIK
            - KIKPW=$KIKPW
            - DATABASE_URL=$DATABASE_URL
            - SECRET_KEY=$SECRET_KEY
            - REDIS_URL=$REDIS_URL
        restart: always
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/mlsb
        depends_on:
            - postgres
            - redis
        command: >
            gunicorn -b 0.0.0.0:8080
                --access-logfile -
                --reload
                "runserver:app"

    postgres:
        restart: always
        image: postgres:10
        environment:
            - POSTGRES_USER=$ADMIN
            - POSTGRES_PASSWORD=$PASSWORD
            - POSTGRES_DB=mlsb
        volumes:
            - "postgres:/data"
        ports:
            - 5433:5432
        expose:
            - 5433
            - 5432

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass devpassword
        volumes:
            - 'redis:/data'
        ports:
            - 6380:6379
        expose:
            - 6380
            - 6379



volumes:
    redis:
    postgres: