name: MLSB Pull-Request Reviews

on: 
  pull_request:
    branches: 
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=20 --max-line-length=127 --statistics --exclude=api/__init__.py,venv/*,cypress-testing/* --ignore=E712,W503,W504
    - name: Test with python unittest
      run: |
        pip install coverage
        coverage run --omit */api/test/*,initDB.py,tqdm.py,api/admin/__init__.py -m unittest discover -s api/test
        coverage report --fail-under=80
        coverage html
    - uses: codecov/codecov-action@v1
      with:
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
    - name: Upload Coverage report
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: htmlcov
    - name: Set up npm
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: UI Test with cypress
      run: |
        export ADMIN="admin"
        export PASSWORD="password"
        # run the server just in-memory
        nohup python runserver.py  2>&1 &
        # now run the cypres tests against it
        cd cypress-testing
        npm install
        npx cypress run --record --key ${{ secrets.CYPRESS_KEY }} --spec "**/*.features" --env ADMIN=admin,PASSWORD=password
    - name: Upload Video Run
      uses: actions/upload-artifact@v1
      with:
        name: cypress-videos
        path: cypress-testing/cypress/videos
