name: MLSB Pull-Request Reviews

on:
  pull_request:
    branches:
      - master
      - main
      - development
  push:
    branches: 
      - master
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=20 --max-line-length=127 --statistics --exclude=api/__init__.py,venv/*,cypress-testing/* --ignore=E712,W503,W504
    - name: Test with python unittest
      run: |
        pip install coverage
        coverage run --omit */api/test/*,initDB.py,tqdm.py,api/admin/__init__.py,venv/* -m unittest discover -s api/test
        coverage report --fail-under=80
        coverage xml
        coverage html
    - name: Create Coverage report Artifact
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: htmlcov
    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        flags: unittests # optional
    - name: Set up npm
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: UI Test with cypress
      run: |
        export ADMIN="admin"
        export PASSWORD="password"
        export FLASK_ENV="development"
        # run the server just in-memory
        nohup python runserver.py  2>&1 &
        # now run the cypres tests against it
        cd cypress-testing
        npm install
        npx cypress run --record --key ${{ secrets.CYPRESS_KEY }} --spec "**/*.features" --env ADMIN=admin,PASSWORD=password
    - name: Upload Video Run
      uses: actions/upload-artifact@v1
      with:
        name: cypress-videos
        path: cypress-testing/cypress/videos
